CREATE TABLE IF NOT EXISTS sale_order
(
    id                  UUID PRIMARY KEY,
    bill_no             TEXT,
    date                TIMESTAMP WITH TIME ZONE,
    create_date         TIMESTAMP WITH TIME ZONE,
    bill_type           TEXT,
    document_status     TEXT,
    customer_number     TEXT,
    customer_name       TEXT,
    sale_department     TEXT,
    customer_country    TEXT,
    province            TEXT,
    city                TEXT,
    material_number     TEXT,
    material_name       TEXT,
    specification_model TEXT,
    unit                TEXT,
    quantity            INTEGER,
    discount_type       TEXT,
    settlement_currency TEXT,
    price               DOUBLE PRECISION,
    amount              DOUBLE PRECISION,
    verify_status       TEXT,
    verify_date         TIMESTAMP WITH TIME ZONE,
    close_status        TEXT,
    close_date          TIMESTAMP WITH TIME ZONE
);